name: Run Bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          LOGIN_1: ${{ secrets.LOGIN_1 }}
          PASSWORD_1: ${{ secrets.PASSWORD_1 }}
          LOGIN_2: ${{ secrets.LOGIN_2 }}
          PASSWORD_2: ${{ secrets.PASSWORD_2 }}
        run: python bot.py

      # 🔥 если бот упал — сохраняем скрин
      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bot-artifacts
          path: |
            error.png
